### PR TITLE
Refactor the `DSLParser` state machine, removing `self.next()`

### PR DESCRIPTION
**Pull request by AlexWaygood**
I don't like the current way the state machine works, at all. The indirection via `self.next()` is a leaky abstraction, as the `state_foo` methods don't really have the same signature at all (or shouldn't, at least). It's also really hard to get your head around and understand if you're not familiar with how clinic works (as I wasn't, until a month or two ago!).

With this refactor, the `state_foo` methods (which are renamed to be `handle_foo` methods) are now able to have different type signatures, removing the need for constant `assert function is not None` assertions everywhere.

- #7

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I didn't take a close look yet (on mobil), but this looks promising. I find the naming slightly off, though. Wouldn't a `parse_` prefix (instead of `handle_`) make it more obvious what's happening?

**Comment by AlexWaygood** [comment]
> Wouldn't a `parse_` prefix (instead of `handle_`) make it more obvious what's happening?

`parse_` is the obvious verb here, yeah, but we've already got a family of methods on the `DSLParser` class with that naming convention (`parse_parameter`, `parse_star`, etc.) which work slightly differently. (They're never called by `self.next()` in the old state machine, and they're never called by `self.parse_line()` in the new one). I wanted to use a different verb for this family of methods to clearly differentiate the two groups of methods.

**Comment by AlexWaygood** [comment]
Probably a more fundamental issue is that the `DSLParser` class is too darn big, and needs to be broken up into several classes (one with the `parse_*` methods, one with the `handle_*` methods, one with the `directive_*` methods). Not wild about tackling that now, though; this PR already feels big enough!

**Comment by AlexWaygood** [comment]
And this of course brings us back to #4: the DSLParser class should probably also be in a separate module...

**Comment by erlend-aasland** [comment]
> Probably a more fundamental issue is that the `DSLParser` class is too darn big, and needs to be broken up into several classes (one with the `parse_*` methods, one with the `handle_*` methods, one with the `directive_*` methods). Not wild about tackling that now, though; this PR already feels big enough!

Yes, we need to break the state machine out of `DSLParser` (or some of the other stuff). For myself, I need to study this for many more weeks until I can even start pointing to a useful refactor :)

**Comment by AlexWaygood** [comment]
Coverage of the `DSLParser` class overall is pretty good both before and after this PR, but some of the new branches I'm adding in `handle_line()` aren't yet covered; I'll need to add coverage for them.

(This reveals another benefit of this PR: it exposes which situations aren't yet being considered by the clinic tests, by unraveling each possibility into a separate branch. Currently all the `state_foo` methods are only ever called via `self.next()`, which makes our coverage stats look better than they really are!)

File: Tools/clinic/clinic.py [hunk 1]
```diff
@@ -4791,23 +4822,33 @@ def state_modulename_name(self, line: str) -> None:
             return_converter = CReturnConverter()
 
         if not module:
-            fail("Undefined module used in declaration of {full_name.strip()!r}.")
-        self.function = Function(name=function_name, full_name=full_name, module=module, cls=cls, c_basename=c_basename,
-                                 return_converter=return_converter, kind=self.kind, coexist=self.coexist)
-        self.block.signatures.append(self.function)
+            fail(f"Undefined module used in declaration of {full_name.strip()!r}.")
```
Comment (AlexWaygood) [inline Tools/clinic/clinic.py:4825]: @erlend-aasland: Another f-string with a missing `f`, introduced in https://github.com/python/cpython/commit/ac7605ed197e8b2336d44c8ac8aeae6faa90a768 😶

Comment (erlend-aasland) [reply Tools/clinic/clinic.py:4825]: I'm unable to trigger this; every case I try is handled by `_module_and_class`, so I get the _"Parent class or module {fullname!r} does not exist."_ error message.

Comment (AlexWaygood) [reply Tools/clinic/clinic.py:4825]: Indeed, `_module_and_class()` returns `tuple[Module | Clinic, Class | None]`. So `module` here is always either an instance of `Module` or `Clinic`, and both `Module` and `Clinic` are always truthy. This branch is, I think, provably unreachable.

Comment (AlexWaygood) [reply Tools/clinic/clinic.py:4825]: > Shouldn't mypy have complained about that?

It has an optional error code `truthy-bool`, which might have complained about it. But it has a higher false-positive rate than most mypy checks, so it's not enabled by default, and I haven't added it to our config file yet. We could try it out, but it might flag some other things in `clinic.py` as well (and it might have some false positives).

Comment (AlexWaygood) [reply Tools/clinic/clinic.py:4825]: Indeed, if we enable that check, then it _does_ complain about this line (and one other line):

```
Tools\clinic\clinic.py:887: error: Member "return_converter" has type "CReturnConverter" which does not implement __bool__ or __len__ so it could always be
true in boolean context  [truthy-bool]
            default_return_converter = (not f.return_converter or
                                            ^~~~~~~~~~~~~~~~~~
Tools\clinic\clinic.py:4779: error: "module" has type Module | Clinic of which no members implement __bool__ or __len__ so it could always be true in
boolean context  [truthy-bool]
            if not module:
                   ^~~~~~
Found 2 errors in 1 file (checked 2 source files)
```

Comment (AlexWaygood) [reply Tools/clinic/clinic.py:4825]: I'll file a PR to enable the `truthy-bool` error code

Comment (AlexWaygood) [reply Tools/clinic/clinic.py:4825]: https://github.com/python/cpython/pull/107627

**Comment by erlend-aasland** [comment]
> Yes, we need to break the state machine out of `DSLParser` (or some of the other stuff). For myself, I need to study this for many more weeks until I can even start pointing to a useful refactor :)

Actually, my suggestion is not a very good one 😄 The parser state machine of course needs to stay in the DSLParser. There are other stuff we can separate out, though.

**Comment by AlexWaygood** [comment]
> Coverage of the `DSLParser` class overall is pretty good both before and after this PR, but some of the new branches I'm adding in `handle_line()` aren't yet covered; I'll need to add coverage for them. Some of them may in fact be unreachable...

After studying the code for a while, I decided that both of the uncovered branches were in fact unreachable -- which indicates that the way the current code in `clinic.py` has some incorrect uses of `self.next()`. I filed https://github.com/python/cpython/pull/107635 to fix that.

**Comment by erlend-aasland** [comment]
> [...] which indicates that the way the current code in `clinic.py` has some incorrect uses of `self.next()` [...]

Well, in a classic state machine, having "setup" states (like param-docstring-start) is IMO correct use of the state machine :)

**Comment by AlexWaygood** [comment]
Okay, following https://github.com/Argument-Clinic/cpython/pull/14/commits/9dc86c8c2ebf81e3ffaab7fd3b8f2d450424d3ae, there are now no new uncovered lines in this PR!
